###
POST http://localhost:3000/api/v2/employee_info/employee_info HTTP/1.1
Content-Type: application/json

{
  "name":"Brayan",
  "lastname":"Ocampo",
  "address":{
    "geo":{
      "lat":"115",
      "ing":"54897"
    },
    "city":"Manizales",
    "code_zip":"4564"
  },
  "department":"5",
  "name_departament":"caldas"
}

###
GET http://localhost:3000/api/v2/employee_info HTTP/1.1

###
GET http://localhost:3000/api/v2/employee_info/6261f0876a770ad7ed4d9fa1 HTTP/1.1

###
PUT http://localhost:3000/api/v2/employee_info/6261f0876a770ad7ed4d9fa1 HTTP/1.1
Content-Type: application/json

{
  "name":"Brayan",
  "lastname":"Ocampo",
  "address":{
    "geo":{
      "lat":"115",
      "ing":"54897",
    },
    "city":"Pereira",
    "code_zip":"4564",
  },
  "department":"5",
  "name_departament":"risaralda",
}

###
DELETE http://localhost:3000/api/v2/employee_info/6261f0876a770ad7ed4d9fa1 HTTP/1.1