###
POST http://localhost:3000/api/v2/series/serie HTTP/1.1
Content-Type: application/json

{
 "serie": "lucifer",
 "number_seasons": 3,
 "original_language": "english",
 "features_seasons":[{
   "season_number": 1,
   "season_name": "lucifer 1",
   "premier_data": "2020-04-02",
   "cast": ["lucifer", "detective"]
 }]
}

###
GET http://localhost:3000/api/v2/series HTTP/1.1

###
GET http://localhost:3000/api/v2/series/62487605d5748f9e7e23c6be HTTP/1.1

###
PUT http://localhost:3000/api/v2/series/62487605d5748f9e7e23c6be HTTP/1.1
Content-Type: application/json

{
 "serie": "lucifer",
 "number_seasons": 3,
 "original_language": "english",
 "features_seasons":[{
   "season_number": 1,
   "season_name": "lucifer 1",
   "premier_data": "2020-04-02",
   "cast": ["lucifer", "detective"]
 }]
}

###
DELETE http://localhost:3000/api/v2/series/62487605d5748f9e7e23c6be HTTP/1.1